### ISSUE TITLE
Parsing FCBs issues.

### ISSUE THREAD

**Issue by tsupplis** [agn453/ZXCC#39]
The current also for parsing fabs in xxcc.c is incorrect. In particular it ignores spaces: The fix is captured below:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/11035456/148782443-5701ae6f-2eee-485d-83ee-16981982931a.png">

```
char *parse_to_fcb(char *s, int afcb)
     RAM[afcb] = 0;
     memset(fcb, ' ', 11);
 
+    while (s[0]==' ')
+    {
+        s++;
+    }
     while (1)
     {
         if (s[0] == 0) break;  
-        if (s[0] == ' ') {++s; continue; }
+        if (s[0] == ' ') break; 
         if (s[1] == ':')
```

**Comment by agn453** [comment]
Fixed in latest commit.  Thanks.
fef0cfa2de73455b66280c8e8870893f1633d4e3
