### ISSUE TITLE
Order of search? local first?

### ISSUE THREAD

**Issue by tsupplis** [agn453/ZXCC#41]
The current zxcc search first for A: and then for P: for COM files. Wouldn't it be more logic to do the contrary?

Here is the suggested fix just switching the order:
```
/*
 * load_comfile() loads the COM file whose name was passed as a parameter.
 *
 */


void load_comfile(void)
{
    size_t com_len;
    char fname[CPM_MAXPATH + 1];
    FILE *fp;

    strcpy(fname, argv[1]);
    fp = try_com(fname);
    if (!fp) 
    {
        strcpy(fname, bindir80);
        strcat(fname, argv[1]);
        fp = try_com(fname);
    }
 ```

**Comment by agn453** [comment]
Changing the default to look for a COM file in the current directory (P:) before the binaries $BINDIR80 one (A:) does make sense to me too.  This will also permit testing of newly built replacement COM files without having to copy them to the binaries subdirectory.  Thanks
f63b212d68339a2df65f778d91c1bd6a914d70b3
