### ISSUE TITLE
zxc program has error message with zxcc rather than zxc

### ISSUE THREAD

**Issue by riwide** [agn453/ZXCC#45]
rwdeane@BARNSLEY:~/zxcc$ zxc -h
zxcc: Cannot locate c.com, c.com.com, c.com.COM, c.com.cpm _or_ c.com.CPM

rwdeane@BARNSLEY:~/zxcc$ zxcc
zxcc: No CP/M program name provided.

**Comment by riwide** [comment]
same for the other programs zxas, zxlibr, zxlink

**Comment by agn453** [comment]
How did you build the ZXCC programs?

If you used the default ```./configure``` command folowed by a ```make``` and ```make install``` then the resulting binaries expect the CP/M programs to be located in the ```/usr/local/lib/cpm/bin80``` directory as well as object libraries (HiTech C *.LIB and *.OBJ) in ```/usr/local/lib/cpm/lib80``` and include files (*.H) in ```/usr/local/lib/cpm/include80```.

All the files need to be stored with lower-case filenames.

You can override the CP/M program directory root by either using (for example) ```./configure --prefix=/Users/tony``` before building and installing (in which case the directories are relative to your home directory - i.e. ```/Users/tony/lib/cpm/bin80``` for the binaries); or define some environment variables that point to alternate locations (e.g. in your .profile or .zprofile file add lines like
```
export BINDIR80=$HOME/lib/cpm/bin80
export LIBDIR80=$HOME/lib/cpm/lib80
export INCDIR80=$HOME/lib/cpm/include80
```
then restart to get these defined when you log in.

I have ZXCC built on my macOS system (configured by specifying the --prefix as above).  What follows is the contents of the directory heirarchy and a test compilation.

```
tony@midi test % ls ~/lib/cpm/bin80 ~/lib/cpm/lib80/ ~/lib/cpm/include80 
/Users/tony/lib/cpm/bin80:
$exec.com       cpp.com         lib.com         options         zip101.com
bios.bin        cref.com        libr.com        p1.com          zsid.com
c.com           debug.com       link.com        rmac.com        zsm4-2.com
c309-11.com     dehuff.com      linq.com        save.com        zsm4-3.com
c309-13.com     drlib.com       m80.com         sdir.com        zsm4-4.com
c309-16.com     drlink.com      mac.com         symtoas.com     zsm4-5.com
c309-17.com     gencom.com      mbasic.com      tkb.com         zsm4-6.com
c309.com        hexcom.com      objtohex.com    unzip157.com    zsm4.com
cgen.com        lbr.com         optim.com       zas.com

/Users/tony/lib/cpm/lib80:
crtcpm.obj      crtcpm.obj-zxcc libc.lib-old    libforig.lib    rrtcpm.obj
crtcpm.obj-8    drtcpm.obj      libcorig.lib    libovr.lib      zxcccpm.obj
crtcpm.obj-9    libc.lib        libf.lib        nrtcpm.obj

/Users/tony/lib/cpm/include80/:
assert.h        float.h         setjmp.h        stdint.h        time.h
conio.h         hitech.h        signal.h        stdio.h         unixio.h
cpm.h           limits.h        stat.h          stdlib.h
ctype.h         math.h          stdarg.h        string.h
exec.h          overlay.h       stddef.h        sys.h
tony@midi test % zxc -o -v testhell.c
Hi-Tech Z80 C Compiler (CP/M-80) V3.09-17
Copyright (C) 1984-87 HI-TECH SOFTWARE
Updated from https://github.com/agn453/HI-TECH-Z80-C
0:CPP -DCPM -DHI_TECH_C -Dz80 -IC: -I P:TESTHELL.C $CTMP1.$$$
0:P1 $CTMP1.$$$ $CTMP2.$$$ $CTMP3.$$$
0:CGEN $CTMP2.$$$ $CTMP1.$$$
0:OPTIM $CTMP1.$$$ $CTMP2.$$$
0:ZAS -J -N -OTESTHELL.OBJ $CTMP2.$$$
ERA $CTMP1.$$$
ERA $CTMP2.$$$
ERA $CTMP3.$$$
ERA $CTMP5.$$$
0:LINQ -Z -Ptext=0,data,bss -C100H -OTESTHELL.COM CRTCPM.OBJ TESTHELL.OBJ LIBC.LIB
ERA TESTHELL.OBJ
ERA $$EXEC.$$$

tony@midi test % zxcc testhell
Hello

tony@midi test % 
```

I hope this helps.

Tony

**Comment by riwide** [comment]
thanks

**Comment by riwide** [comment]
just git clone; cd into directory, ./configure; make all; sudo make install.

just trying these for the first time to try nulu and some checksum
utilities.

I am trying to assemble a set of nevada (jrt) pascal 4.1 files from Amstrad
CPC disks, for generic use. So far one extraction works and another seems
to give some corruption, hence the thought of testing under linux quickly
and doing checksum comparisons.

I tend to run Linux Mint (Ubuntu) or Windows 11 with Debian bookworm on
chromebook or pi5. I am trying to free myself from Windows but have not
achieved all alternative programs yet - Altera Quartus II is the biggie
(for Multicomp) - supposed to run on Linux but hangs for me at 11%

Thanks for your help
Richard
